services:
  db-facturacion:
    container_name: db-facturacion
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: facturacion
      POSTGRES_USER: usuario_facturacion
      POSTGRES_PASSWORD: contrasena_facturacion
    networks:
      facturacion-network:
        ipv4_address: 172.21.0.2
    ports:
      - "5431:5432"
    expose:
      - "5431"
    # Añadir healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario_facturacion -d facturacion -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: .
    ports:
      - "3000:3000"
    networks:
      facturacion-network:
        ipv4_address: 172.21.0.3
    depends_on:
      db-facturacion:
        condition: service_healthy
    restart: always

networks:
  facturacion-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24