spring.application.name=sistema-facturacion

server.port=8083

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5431/facturacion
spring.datasource.username=usuario_facturacion
spring.datasource.password=contrasena_facturacion


# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=public
spring.liquibase.enabled=true